# Permalinks
#
permalink:           pretty

# Setup
title:               Riot.js
tagline:             Simple and elegant component-based UI library
url:                 http://riotjs.com
baseurl:             ""

# Markdown
markdown:           kramdown
extensions:         [fenced_code_blocks]
redcarpet:
  extensions:       [with_toc_data,autolink,smart]

# Handling Reading
safe:               false
include:            [".htaccess"]
exclude:            ["*.tag"]
encoding:           "utf-8"
markdown_ext:       "markdown,md"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         style
  style:            :compressed

gems:
  - jemoji

# About/contact
author:
  name:              Riot
  url:               http://riotjs.com
  email:             hello.riotjs@gmail.com

# Custom vars
minor_version:       2.6
v2_minor_version:    2.6

version:             2.6.7
v2_version:          2.6.7
release_date:        November 6
version_slurp:       Fix rendering of tags containing SVGs
repo:                https://github.com/riot/riot
twitter_account:     https://twitter.com/riotjs_
gitter:              https://gitter.im/riot/riot
# Vars needed for the compare.md page

size_min:            9.39
riot_route_size_min: 1.77

polymer:
  size: 45.69 # according to https://github.com/riot/riot/issues/1575#issuecomment-180869792
  version: 1.6.1

webcomponents:
  size:    12.39
  version: 0.7.22

polymer_and_webcomponents_size: 58.08 # 45.69 + 12.39 (polymer + webcomponents-lite.min.js )

react:
  size:    44.32
  version: 15.3.1

react_router:
  size:    14.13
  version: 2.6.1

react_mini_router:
  size:    3.93
  version: 2.0.0


# precalculated round values because of {{round}} liquid filter bug
compare:
  react: 5 # react.size / size_min
  react_router_vs_riot_router: 8 # react_router.size / riot_route_size_min
  polymer_and_webcomponents: 6 # polymer_and_webcomponents_size / size_min

# Languages
translations:
  es: v2.2.4
  fr: v2.5.0
  ja: v2.3.12
  ru: v2.3.1
  zh: v2.3.1
  zh: v2.3.13
