# Permalinks
#
permalink:           pretty

# Setup
title:               Riot.js
tagline:             A React-like, user interface microlibrary
url:                 http://riotjs.com
baseurl:             ""

# Markdown
markdown:           redcarpet
extensions:         [fenced_code_blocks]
redcarpet:
  extensions:       [with_toc_data,autolink,smart]

# Handling Reading
safe:               false
include:            [".htaccess"]
exclude:            ["*.tag"]
encoding:           "utf-8"
markdown_ext:       "markdown,md"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         style
  style:            :compressed

# About/contact
author:
  name:              Riot
  url:               http://riotjs.com
  email:             hello.riotjs@gmail.com

# Custom vars
major_version:       1
minor_version:       2.3

version:             2.3.1
release_date:        November 10
version_slurp:       Babel 6 support - bug fix
repo:                https://github.com/riot/riot

# Vars needed for the compare.md page

size_min:            18.00
riot_route_size_min: 2.93

polymer:
  size:    112.00
  version: 1.2.1

webcomponents:
  size:    117.00
  version: 0.7.15

polymer_and_webcomponents_size: 229 # 112 + 117

react:
  size:    135.00
  version: 0.14.1

react_router:
  size:    36.00
  version: 0.13.4

react_mini_router:
  size:    7.98
  version: 1.1.7


# precalculated round values because of {{round}} liquid filter bug
compare:
  react: 8 # react.size / size_min
  react_router_vs_riot_router: 12 # react_router.size / riot_route_size_min
  react_mini_router_vs_riot_router: 12 # react_router.size / riot_route_size_min
  polymer_and_webcomponents: 13 # polymer_and_webcomponents_size / size_min

# Languages
translations:
  fr: v2.3.1
  ja: v2.2.3
  ru: v2.3.1
  zh: v2.3.1
