# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty
relative_permalinks: true

# Setup
title:               Riot.js
tagline:             A React-like, user interface microlibrary
url:                 http://riotjs.com
baseurl:             ""

# Markdown
markdown:           redcarpet
extensions:         [fenced_code_blocks]

# Handling Reading
safe:               false
include:            [".htaccess"]
exclude:            ["*.tag"]
encoding:           "utf-8"
markdown_ext:       "markdown,md"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         style
  style:            :compressed

# About/contact
author:
  name:              Riot
  url:               http://riotjs.com
  email:             riotjs@gmail.com

# Custom vars
version:             2.3.0
repo:                https://github.com/riot/riot
